export const OBJECT_TYPE = {
  "FACE":1,
  "PEDESTRIAN":2,
  "AUTOMOBILE":3,
  "CYCLIST":4,
  "HUMAN_POWERED_VEHICLE":5,
};
export const PreviewInfoObjectMap = {
  1 /*ObjectType.OBJECT_FACE*/: {
    name: "OBJECT_FACE",
    title: "人脸数据",
    attrs: {
      gender_code: "性别",
      st_age: "年龄",
      // skin_color: "肤色",
      glass_style: "眼镜款式",
      // ethic_code: "民族",
      mustache_style: "胡型",
      respirator_color: "口罩",
      cap_style: "帽子款式",
    },
    color: "red",
    completion: "色",
    rectWidthLimit:30,
    lineWidth: 3,
    opacity: 0,
  },
  2 /*ObjectType.OBJECT_PEDESTRIAN*/: {
    name: "OBJECT_PEDESTRIAN",
    title: "行人数据",
    attrs: {
      hair_color: "发色",
      hair_style: "发型",
      cap_style: "帽子款式",
      bag_style: "包款式",
      appendant: "附属物",
      st_coat_pattern: "上衣图案",
      st_trousers_pattern: "下装图案",
      coat_style: "上衣款式",
      coat_length: "上衣长度",
      trousers_len: "下装长度",
      cap_color: "帽子颜色",
      bag_color: "包颜色",
      umbrella_color: "伞颜色",
      coat_color: "上衣颜色",
      shoes_color: "鞋子颜色",
      respirator_color: "口罩颜色",
      shoes_style: "鞋子款式",
      trousers_color: "下装颜色",
      gender_code: "性别",
      // st_age: "年纪",
    },
    // 组装结果
    assemble: {
      gender: {
        // label: "性别",
        showField: ["gender_code"],
      },
      hair: {
        label: "头发",
        showField: ["hair_color", "hair_style"],
        completion: "色",
      },
      coat: {
        label: "上衣",
        showField: ["coat_color", "coat_style", "coat_length"],
        completion: "色",
      },
      trousers: {
        label: "下装",
        showField: ["trousers_color", "trousers_len"],
        completion: "色",
      },
      shoes: {
        label: "鞋子",
        showField: ["shoes_color", "shoes_style"],
        completion: "色",
      },
      bag: {
        label: "包",
        showField: ["bag_color", "bag_style"],
        completion: "色",
      },
      cap: {
        label: "帽子",
        showField: ["cap_color", "cap_style"],
        completion: "色",
      },
      umbrella: {
        label: "伞",
        showField: ["umbrella_color"],
        completion: "色",
      },
      umbrella: {
        label: "口罩",
        showField: ["respirator_color"],
        completion: "色",
      },
    },
    color: "yellow",
    rectWidthLimit:40,
    lineWidth: 3,
    opacity: 0,
  },
  3 /*ObjectType.OBJECT_AUTOMOBILE*/: {
    name: "OBJECT_AUTOMOBILE",
    title: "机动车数据",
    attrs: {
      // vehicle_brand: "车辆品牌",
      vehicle_model: "车辆型号",
      vehicle_color: "车辆颜色",
      vehicle_class: "车辆类型",
      plate_no: "车牌",
    },
    // 不需要匹配过滤，直接展示的字段
    noFiltration: ["vehicle_model", "plate_no"],
    color: "blue",
    completion: "色",
    rectWidthLimit:100,
    lineWidth: 3,
    opacity: 0,
  },
  4 /*ObjectType.OBJECT_CYCLIST*/: {
    name: "OBJECT_CYCLIST",
    title: "骑手数据",
    attrs: {
      //st_direction: '方向',
      coat_color: "外衣颜色",
      hair_color: "头发颜色",
      hair_style: "发型",
      gender_code: "性别",
      st_age: "年纪",
      shoes_color: "鞋颜色",
    },
    color: "red",
    completion: "色",
    rectWidthLimit:50,
    lineWidth: 3,
    opacity: 0,
  },
  5 /*ObjectType.OBJECT_HUMAN_POWERED_VEHICLE*/: {
    name: "OBJECT_HUMAN_POWERED_VEHICLE",
    title: "非机动车数据",
    attrs: {
      // st_direction: "方向",
      vehicle_color: "车身颜色",
      st_vehicle_class: "车辆类型",
    },
    color: "orange",
    completion: "色",
    rectWidthLimit:60,
    lineWidth: 3,
    opacity: 0,
  },
};

export const PreviewInfoEventMap = {
  1 /* EventType.EVENT_PEDESTRIAN_STAY */: {
    name: "EVENT_PEDESTRIAN_STAY",
    title: "逗留事件",
    tips: "逗留",
    color: "orange",
    lineWidth: 3,
    opacity: 0,
  },
  2 /* EventType.EVENT_PEDESTRIAN_HOVER */: {
    name: "EVENT_PEDESTRIAN_HOVER",
    title: "徘徊事件",
    tips: "徘徊",
    color: "yellow",
    lineWidth: 3,
    opacity: 0,
  },
  3 /* EventType.EVENT_PEDESTRIAN_CROSS_LINE */: {
    name: "EVENT_PEDESTRIAN_CROSS_LINE",
    title: "越线事件",
    tips: "越线",
    color: "orange",
    lineWidth: 3,
    opacity: 0,
  },
  4 /* EventType.EVENT_PEDESTRIAN_INVADE */: {
    name: "EVENT_PEDESTRIAN_INVADE",
    title: "区域入侵事件",
    tips: "区域入侵",
    color: "blue",
    lineWidth: 3,
    opacity: 0,
  },
  5 /* EventType.EVENT_VEHICLE_PARK */: {
    name: "EVENT_VEHICLE_PARK",
    title: "违停事件",
    //tips:"违停事件",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  50 /* EventType.EVENT_CROWD_DENSITY */: {
    name: "EVENT_CROWD_DENSITY",
    title: "人群过密事件",
    tips: "人群过密",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  51 /* EventType.EVENT_CROWD_STRAND */: {
    name: "EVENT_CROWD_STRAND",
    title: "人群滞留事件",
    tips: "人群滞留",
    color: "yellow",
    lineWidth: 3,
    opacity: 0,
  },
};

export const PreviewInfoScenarioMap = {
  0 /* ScenarioType.ST_UNKNOWN */: {
    name: "未知",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  1 /* ScenarioType.ST_STALL */: {
    name: "违规占道经营",
    //tips:"占道经营事件",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  2 /* ScenarioType.ST_FIRE */: {
    name: "烟火",
    //tips:"烟火检测事件",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  3 /* ScenarioType.ST_SLOGAN */: {
    name: "臧疆标语检测",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  4 /* ScenarioType.ST_LANDSCAPE_LAMP */: {
    name: "景观灯损坏",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  5 /* ScenarioType.ST_CLUTTER */: {
    name: "工地堆放不当",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  6 /* ScenarioType.ST_ROAD_CLEAN */: {
    name: "路面清洁",
    //tips:"工程车抛洒事件",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  7 /* ScenarioType.ST_SOIL */: {
    name: "工地泥土覆盖",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  8 /* ScenarioType.ST_GARBAGE */: {
    name: "打包垃圾检测",
    //tips:"垃圾满溢事件",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  9 /* ScenarioType.ST_SHARED_BICYCLE */: {
    name: "共享单车分类 ",
    //tips:"共享单车违停",
    color: "red",
    lineWidth: 3,
    opacity: 0,
  },
  10 /* ScenarioType.ST_SHARED_BICYCLE_MISORDER */: {
    name: "共享单车乱序摆放",
    //tips:"共享单车成片倾倒事件",
    color: "red",
    lineWidth: 1,
    opacity: 0,
  },
};

export const TextStyle = {
  //文字框背景颜色
  textBackgroundColor: "#00000044",
  //文字配置
  textFont: "16px Arial",
  //文字框宽度
  //textFrameWidth:120,
  //文字框每行递增
  textFrameInterval: 20,
  //文字框每行高度
  textFrameHeightPerLine: 20,
  //行间隔
  lineSpace: 2,
  //文字颜色
  textColor: "#FFFFFF",
};

export const EventStyle = {
  //持续时间,单位毫秒
  eventTime: 500,
  //告警颜色
  eventColor: "red",
  //文字框背景颜色
  textBackgroundColor: "#000000CC",
  //文字配置
  textFont: "16px Arial",
  //文字框宽度
  //textFrameWidth:80,
  //文字框每行递增
  textFrameInterval: 30,
  //文字框每行高度
  textFrameHeightPerLine: 20,
  //文字颜色
  textColor: "#FFFFFF",
  //透明度变化速度
  opacitySpeed: 0.002,
};

export const HeatmapStyle = {
  //文字内容
  content: "关注区域内人数：",
  //文字配置
  textFont: "bold 36px Arial",
  //距离上边
  top: 50,
  //距离右边
  left: 20,
  //文字颜色
  textColor: "#FF0000",
  textWidth: 200,
  textHeight: 40,
};

export const StructedFearureValue = {
  //color
  BLACK: "黑",
  WHITE: "白",
  GRAY: "灰",
  RED: "红",
  BLUE: "蓝",
  YELLOW: "黄",
  ORANGE: "橙",
  BROWN: "棕",
  GREEN: "绿",
  PURPPLE: "紫",
  CYAN: "青",
  PINK: "粉",
  TRANSPARENT: "透明",
  COLOR_TYPE_OTHER: "有", //'其他'
  COLOR_TYPE_NONE: "无",
  //gender_code
  MALE: "男",
  FEMALE: "女",
  //st_age
  ST_OLD: "老年人",
  ST_ADULT: "成年人",
  ST_CHILD: "小孩",
  ST_AGE_TYPE_OTHER: "其他",
  //mustache_style
  MUSTACHE_STYLE_TYPE_NONE: "无胡子",
  WHISKERS: "络腮胡",
  MUSTACHE_STYLE_TYPE_OTHER: "其他",
  //glass_style
  GLASSES_STYLE_TYPE_NONE: "无眼镜",
  SUNGLASSES: "太阳镜",
  TRANSPARENT_GLASSES: "普通眼镜", //'透明色',
  GLASSES_STYLE_TYPE_OTHER: "其他",
  //hair_style
  BALD: "全秃",
  LONG: "披肩",
  ST_SHORT: "短发",
  //vehicle_class
  ST_CAR: "轿车",
  ST_VAN: "厢式货车",
  ST_SMALL_TRUCK: "小卡车",
  ST_BIG_TRUCK: "大卡车",
  ST_SUV: "运动型多功能车",
  ST_BIG_BUS: "大型公共汽车",
  ST_MED_BUS: "中型公共汽车",
  ST_AUTOMOBILE_TYPE_OTHER: "其他",
  //st_vehicle
  ST_MOTOR: "摩托车",
  ST_EBIKE: "电动车",
  ST_BICYCLE: "自行车",
  ST_TRICYCLE: "三轮车",
  ST_HUMAN_POWERED_VEHICLE_TYPE_OTHER: "其他",
  //cap_style
  HAT_STYLE_TYPE_NONE: "无",
  BUCKET_HAT: "渔夫帽",
  BONNET: "套头帽",
  CAP: "鸭舌帽",
};

export const Console = {
  isConsole: true,
  consoleStructure: true,
  consoleEventRule: true,
  consoleEvent: true,
  consoleCrowd: true,
  consoleScenario: true,
};
export const ATTRS_RECT_CONFIG = {
  textFont:"12px SourceHanSansCN",
  textColor:"#D5D5D5",
  textBaseline:"middle",
  textDirection:"inherit",
  fillColor:"rgba(59,71,100,0.8)",
  lineColor:"#56668D",
  textIndent:20,
  attrRectW:124,
  attrRectH:28,
  radius:4,
  titleR:3,
};
export const NONE_KEY = "_NONE";
export const attribute_value_definition = [
  { key: "COLOR_TYPE_NONE", value: "null" },
  { key: "BLACK", value: "黑" },
  { key: "WHITE", value: "白" },
  { key: "GRAY", value: "灰" },
  { key: "RED", value: "红" },
  { key: "BLUE", value: "蓝" },
  { key: "YELLOW", value: "黄" },
  { key: "ORANGE", value: "橙" },
  { key: "BROWN", value: "棕" },
  { key: "GREEN", value: "绿" },
  { key: "PURPLE", value: "紫" },
  { key: "CRAN", value: "青" },
  { key: "PINK", value: "粉" },
  { key: "TRANSPARENT", value: "透明" },
  { key: "COLOR_TYPE_OTHER", value: "其他" },
  { key: "ST_ANGLE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_FRONT", value: "正面" },
  { key: "ST_SIDE", value: "侧面" },
  { key: "ST_BACK", value: "后面" },
  { key: "ST_ANGLE_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "ST_AUTOMOBILE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_CAR", value: "三厢轿车" },
  { key: "ST_VAN", value: "面包车/MPV" },
  { key: "ST_SMALL_TRUCK", value: "皮卡" },
  { key: "ST_BIG_TRUCK", value: "卡车" },
  { key: "ST_SUV", value: "两厢轿车/SUV" },
  { key: "ST_BIG_BUS", value: "巴士" },
  { key: "ST_MED_BUS", value: "中型公共汽车" },
  { key: "ST_AUTOMOBILE_TYPE_OTHER", value: "其他" },
  { key: "ST_HUMAN_POWERED_VEHICLE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_MOTOR", value: "摩托车" },
  { key: "ST_EBIKE", value: "电动车" },
  { key: "ST_BICYCLE", value: "自行车" },
  { key: "ST_TRICYCLE", value: "三轮车" },
  { key: "ST_HUMAN_POWERED_VEHICLE_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "GENDER_TYPE_NONE", value: "未知的性别" },
  { key: "MALE", value: "男" },
  { key: "FEMALE", value: "女" },
  { key: "GENDER_TYPE_OTHER", value: "未说明的性别" },
  { key: "MUSTACHE_STYLE_TYPE_NONE", value: "无胡子" },
  { key: "A_WORD_OF_BEARD", value: "一字胡" },
  { key: "HANDLEBAR", value: "八字胡" },
  { key: "STUBBLE", value: "淡胡子" },
  { key: "WHISKERS", value: "络腮胡" },
  { key: "GOATTE", value: "山羊胡" },
  { key: "GRAY_BEARD", value: "花白胡" },
  { key: "SOUL_PATCH", value: "一点胡" },
  { key: "MUSTACHE_STYLE_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "HAIR_STYLE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "CREW_CUT", value: "平头" },
  { key: "MIDDLE", value: "中分" },
  { key: "SIDEPART", value: "偏分" },
  { key: "FORE_HEAD_NOHAIR", value: "额秃" },
  { key: "TOP_NOHAIR", value: "顶秃" },
  { key: "BALD", value: "全秃" },
  { key: "CURLY_HAIR", value: "卷发" },
  { key: "WAVY_HAIR", value: "波浪发" },
  { key: "BRAIRD", value: "麻花辫" },
  { key: "WEAR_HAIR", value: "盘发" },
  { key: "LONG", value: "披肩" },
  { key: "HAIR_STYLE_TYPE_OTHER", value: "其他" },
  { key: "ST_SHORT", value: "短发" },
  { key: "APPENDAGE_TYPE_NONE", value: "无附属品" },
  { key: "MOBILE", value: "手机" },
  { key: "UMBRELLA", value: "伞" },
  { key: "RESPIRATOR", value: "口罩" },
  { key: "WATCH", value: "手表" },
  { key: "HELMET", value: "头盔" },
  { key: "GLASSES", value: "眼镜" },
  { key: "HAT", value: "帽子" },
  { key: "BAG", value: "包" },
  { key: "SCARF", value: "围巾" },
  { key: "APPENDAGE_TYPE_OTHER", value: "其他" },
  { key: "GLASSES_STYLE_TYPE_NONE", value: "无眼镜" },
  { key: "FULL_FRAME", value: "全框" },
  { key: "HALF_FRAME", value: "半框" },
  { key: "RIMELESS_FRAME", value: "无框" },
  { key: "SUPEROLATERAL", value: "眉线框" },
  { key: "MULTIFUNCTION", value: "多功能框" },
  { key: "PHOTOCHROMIC", value: "变色镜" },
  { key: "SUNGLASSES", value: "太阳镜" },
  { key: "LENSLESS_GLASSES", value: "无镜片" },
  { key: "TRANSPARENT_GLASSES", value: "透明色" },
  { key: "GLASSES_STYLE_TYPE_OTHER", value: "其他" },
  { key: "BAG_STYLE_TYPE_NONE", value: "无背包" },
  { key: "SHOULDER_BAG", value: "单肩包" },
  { key: "HAND_BAG", value: "手提包" },
  { key: "BACKPACK", value: "双肩包" },
  { key: "WALLET", value: "钱包" },
  { key: "HAND_HELD_BAG", value: "手拿包" },
  { key: "WAIST_PACK", value: "腰包" },
  { key: "KEY_BAG", value: "钥匙包" },
  { key: "CARD_BAG", value: "卡包" },
  { key: "TROLLEY", value: "手拉箱" },
  { key: "TRAVELLING_BAG", value: "旅行包" },
  { key: "COWBOY_BAG", value: "牛仔包" },
  { key: "MESSAGE_BAG", value: "斜挎包" },
  { key: "BAG_STYLE_TYPE_OTHER", value: "其他" },
  { key: "COAT_LENGTH_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "LONG_SLEEVE", value: "长袖" },
  { key: "SHORT_SLEEVE", value: "短袖" },
  { key: "SLEEVELESS", value: "无袖" },
  { key: "COAT_LENGTH_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "PANTS_LENGTH_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "TROUSERS", value: "长裤" },
  { key: "SHORTS", value: "短裤" },
  { key: "PANTS_LENGTH_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "ST_SKIRT", value: "裙子" },
  { key: "ST_PATTERN_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_PURE", value: "纯色" },
  { key: "ST_STRIPE", value: "条纹" },
  { key: "ST_DESIGN", value: "图案" },
  { key: "ST_JOINT", value: "拼接" },
  { key: "ST_LATTIC", value: "格子" },
  { key: "ST_PATTERN_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "SHOES_STYLE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "BOARD_SHOE", value: "板鞋" },
  { key: "LEATHER_SHOES", value: "皮鞋" },
  { key: "SPORTS_SHOES", value: "运动鞋" },
  { key: "SLIPPER", value: "拖鞋" },
  { key: "SANDAL", value: "凉鞋" },
  { key: "WALKING_SHOES", value: "休闲鞋" },
  { key: "BOOTS", value: "高筒靴" },
  { key: "COMBAT_BOOTS", value: "中筒靴" },
  { key: "SHORT_BOOTS", value: "低筒靴" },
  { key: "HIKING_BOOTS", value: "登山靴" },
  { key: "SOLDIER_BOOTS", value: "军装靴" },
  { key: "NO_BOOTS", value: "无靴子" },
  { key: "SHOES_STYLE_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "HAT_STYLE_TYPE_NONE", value: "无帽子" },
  { key: "WOOLEN_HAT", value: "毛线帽" },
  { key: "BERET", value: "贝雷帽" },
  { key: "BASEBALL_CAP", value: "棒球帽" },
  { key: "FLAT_TOP_CAP", value: "平顶帽" },
  { key: "BUCKET_HAT", value: "渔夫帽" },
  { key: "BONNET", value: "套头帽" },
  { key: "CAP", value: "鸭舌帽" },
  { key: "BROAD_BRIMMED_HAT", value: "大檐帽" },
  { key: "ST_HARD_HAT", value: "安全帽" },
  { key: "HAT_STYLE_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "COAT_STYLE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "BUSINESS_SUIT", value: "西装" },
  { key: "NATION_CLOTHES", value: "民族服" },
  { key: "T_SHIRT", value: "T恤" },
  { key: "SHIRT", value: "衬衫" },
  { key: "FLEECE", value: "卫衣" },
  { key: "JACKET", value: "夹克" },
  { key: "LEATHER_JECKET", value: "皮夹克" },
  { key: "LONG_COAT", value: "大衣" },
  { key: "WIND_COAT", value: "风衣" },
  { key: "SWEATER", value: "毛衣" },
  { key: "COTTON_PADDED_CLOTHES", value: "棉衣" },
  { key: "DOWN_JACKET", value: "羽绒服" },
  { key: "SPORTS_WEARS", value: "运动服" },
  { key: "WORK_CLOTHES", value: "工作服" },
  { key: "COWBOY_CLOTHES", value: "牛仔服" },
  { key: "SLEEPWEAR", value: "睡衣" },
  { key: "DRESS", value: "连衣裙" },
  { key: "NOT_LONG_COAT", value: "无上衣" },
  { key: "COAT_STYLE_TYPE_OTHER", value: "其他" },
  { key: "ST_EXPRESSION_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_ANGRY", value: "生气" },
  { key: "ST_HAPPY", value: "高兴" },
  { key: "ST_SORROW", value: "悲伤" },
  { key: "ST_CALM", value: "平静" },
  { key: "ST_SURPRISED", value: "惊讶" },
  { key: "ST_CONFUSED", value: "困惑" },
  { key: "ST_DISGUST", value: "厌恶" },
  { key: "ST_SCARED", value: "害怕" },
  { key: "ST_SQUINT", value: "斜视" },
  { key: "ST_SCREAM", value: "尖叫" },
  { key: "ST_EXPRESSION_TYPE_OTHER", value: "其他" },
  { key: "ST_STATUS_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_OPEN", value: "打开" },
  { key: "ST_CLOSE", value: "关闭" },
  { key: "ST_STATUS_TYPE_OTHER", value: "保留字段，暂未使用" },
  { key: "ST_AGE_TYPE_NONE", value: "保留字段，暂未使用" },
  { key: "ST_OLD", value: "老年人" },
  { key: "ST_ADULT", value: "成年人" },
  { key: "ST_CHILD", value: "小孩" },
  { key: "ST_AGE_TYPE_OTHER", value: "保留字段，暂未使用" },
];
export const ALL_ATTRS_VALUE = {
  COLOR_TYPE_NONE: "null",
  BLACK: "黑",
  WHITE: "白",
  GRAY: "灰",
  RED: "红",
  BLUE: "蓝",
  YELLOW: "黄",
  ORANGE: "橙",
  BROWN: "棕",
  GREEN: "绿",
  PURPLE: "紫",
  CRAN: "青",
  PINK: "粉",
  TRANSPARENT: "透明",
  COLOR_TYPE_OTHER: "其他",
  ST_ANGLE_TYPE_NONE: "保留字段，暂未使用",
  ST_FRONT: "正面",
  ST_SIDE: "侧面",
  ST_BACK: "后面",
  ST_ANGLE_TYPE_OTHER: "保留字段，暂未使用",
  ST_AUTOMOBILE_TYPE_NONE: "保留字段，暂未使用",
  ST_CAR: "三厢轿车",
  ST_VAN: "面包车/MPV",
  ST_SMALL_TRUCK: "皮卡",
  ST_BIG_TRUCK: "卡车",
  ST_SUV: "两厢轿车/SUV",
  ST_BIG_BUS: "巴士",
  ST_MED_BUS: "中型公共汽车",
  ST_AUTOMOBILE_TYPE_OTHER: "其他",
  ST_HUMAN_POWERED_VEHICLE_TYPE_NONE: "保留字段，暂未使用",
  ST_MOTOR: "摩托车",
  ST_EBIKE: "电动车",
  ST_BICYCLE: "自行车",
  ST_TRICYCLE: "三轮车",
  ST_HUMAN_POWERED_VEHICLE_TYPE_OTHER: "保留字段，暂未使用",
  GENDER_TYPE_NONE: "未知的性别",
  MALE: "男",
  FEMALE: "女",
  GENDER_TYPE_OTHER: "未说明的性别",
  MUSTACHE_STYLE_TYPE_NONE: "无胡子",
  A_WORD_OF_BEARD: "一字胡",
  HANDLEBAR: "八字胡",
  STUBBLE: "淡胡子",
  WHISKERS: "络腮胡",
  GOATTE: "山羊胡",
  GRAY_BEARD: "花白胡",
  SOUL_PATCH: "一点胡",
  MUSTACHE_STYLE_TYPE_OTHER: "保留字段，暂未使用",
  HAIR_STYLE_TYPE_NONE: "保留字段，暂未使用",
  CREW_CUT: "平头",
  MIDDLE: "中分",
  SIDEPART: "偏分",
  FORE_HEAD_NOHAIR: "额秃",
  TOP_NOHAIR: "顶秃",
  BALD: "全秃",
  CURLY_HAIR: "卷发",
  WAVY_HAIR: "波浪发",
  BRAIRD: "麻花辫",
  WEAR_HAIR: "盘发",
  LONG: "披肩",
  HAIR_STYLE_TYPE_OTHER: "其他",
  ST_SHORT: "短发",
  APPENDAGE_TYPE_NONE: "无附属品",
  MOBILE: "手机",
  UMBRELLA: "伞",
  RESPIRATOR: "口罩",
  WATCH: "手表",
  HELMET: "头盔",
  GLASSES: "眼镜",
  HAT: "帽子",
  BAG: "包",
  SCARF: "围巾",
  APPENDAGE_TYPE_OTHER: "其他",
  GLASSES_STYLE_TYPE_NONE: "无眼镜",
  FULL_FRAME: "全框",
  HALF_FRAME: "半框",
  RIMELESS_FRAME: "无框",
  SUPEROLATERAL: "眉线框",
  MULTIFUNCTION: "多功能框",
  PHOTOCHROMIC: "变色镜",
  SUNGLASSES: "太阳镜",
  LENSLESS_GLASSES: "无镜片",
  TRANSPARENT_GLASSES: "普通眼镜",  //'透明色'
  GLASSES_STYLE_TYPE_OTHER: "其他",
  BAG_STYLE_TYPE_NONE: "无背包",
  SHOULDER_BAG: "单肩包",
  HAND_BAG: "手提包",
  BACKPACK: "双肩包",
  WALLET: "钱包",
  HAND_HELD_BAG: "手拿包",
  WAIST_PACK: "腰包",
  KEY_BAG: "钥匙包",
  CARD_BAG: "卡包",
  TROLLEY: "手拉箱",
  TRAVELLING_BAG: "旅行包",
  COWBOY_BAG: "牛仔包",
  MESSAGE_BAG: "斜挎包",
  BAG_STYLE_TYPE_OTHER: "其他",
  COAT_LENGTH_TYPE_NONE: "保留字段，暂未使用",
  LONG_SLEEVE: "长袖",
  SHORT_SLEEVE: "短袖",
  SLEEVELESS: "无袖",
  COAT_LENGTH_TYPE_OTHER: "保留字段，暂未使用",
  PANTS_LENGTH_TYPE_NONE: "保留字段，暂未使用",
  TROUSERS: "长裤",
  SHORTS: "短裤",
  PANTS_LENGTH_TYPE_OTHER: "保留字段，暂未使用",
  ST_SKIRT: "裙子",
  ST_PATTERN_TYPE_NONE: "保留字段，暂未使用",
  ST_PURE: "纯色",
  ST_STRIPE: "条纹",
  ST_DESIGN: "图案",
  ST_JOINT: "拼接",
  ST_LATTIC: "格子",
  ST_PATTERN_TYPE_OTHER: "保留字段，暂未使用",
  SHOES_STYLE_TYPE_NONE: "保留字段，暂未使用",
  BOARD_SHOE: "板鞋",
  LEATHER_SHOES: "皮鞋",
  SPORTS_SHOES: "运动鞋",
  SLIPPER: "拖鞋",
  SANDAL: "凉鞋",
  WALKING_SHOES: "休闲鞋",
  BOOTS: "高筒靴",
  COMBAT_BOOTS: "中筒靴",
  SHORT_BOOTS: "低筒靴",
  HIKING_BOOTS: "登山靴",
  SOLDIER_BOOTS: "军装靴",
  NO_BOOTS: "无靴子",
  SHOES_STYLE_TYPE_OTHER: "保留字段，暂未使用",
  HAT_STYLE_TYPE_NONE: "无帽子",
  WOOLEN_HAT: "毛线帽",
  BERET: "贝雷帽",
  BASEBALL_CAP: "棒球帽",
  FLAT_TOP_CAP: "平顶帽",
  BUCKET_HAT: "渔夫帽",
  BONNET: "套头帽",
  CAP: "鸭舌帽",
  BROAD_BRIMMED_HAT: "大檐帽",
  ST_HARD_HAT: "安全帽",
  HAT_STYLE_TYPE_OTHER: "保留字段，暂未使用",
  COAT_STYLE_TYPE_NONE: "保留字段，暂未使用",
  BUSINESS_SUIT: "西装",
  NATION_CLOTHES: "民族服",
  T_SHIRT: "T恤",
  SHIRT: "衬衫",
  FLEECE: "卫衣",
  JACKET: "夹克",
  LEATHER_JECKET: "皮夹克",
  LONG_COAT: "大衣",
  WIND_COAT: "风衣",
  SWEATER: "毛衣",
  COTTON_PADDED_CLOTHES: "棉衣",
  DOWN_JACKET: "羽绒服",
  SPORTS_WEARS: "运动服",
  WORK_CLOTHES: "工作服",
  COWBOY_CLOTHES: "牛仔服",
  SLEEPWEAR: "睡衣",
  DRESS: "连衣裙",
  NOT_LONG_COAT: "无上衣",
  COAT_STYLE_TYPE_OTHER: "其他",
  ST_EXPRESSION_TYPE_NONE: "保留字段，暂未使用",
  ST_ANGRY: "生气",
  ST_HAPPY: "高兴",
  ST_SORROW: "悲伤",
  ST_CALM: "平静",
  ST_SURPRISED: "惊讶",
  ST_CONFUSED: "困惑",
  ST_DISGUST: "厌恶",
  ST_SCARED: "害怕",
  ST_SQUINT: "斜视",
  ST_SCREAM: "尖叫",
  ST_EXPRESSION_TYPE_OTHER: "其他",
  ST_STATUS_TYPE_NONE: "保留字段，暂未使用",
  ST_OPEN: "打开",
  ST_CLOSE: "关闭",
  ST_STATUS_TYPE_OTHER: "保留字段，暂未使用",
  ST_AGE_TYPE_NONE: "保留字段，暂未使用",
  ST_OLD: "老年人",
  ST_ADULT: "成年人",
  ST_CHILD: "小孩",
  ST_AGE_TYPE_OTHER: "保留字段，暂未使用",
};
